title:            NJUST Vision & Graph Group
description:      Describe your website here.

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/LabName.JPG # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://fakeroy.github.io/

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/Introduction'
  - title: 'News'
    url: '/pages/News'
  - title: 'Teachers'
    url: '/pages/Teacher'
    submenu:
      - title: 'Zhen Cui'
        url: '/pages/Teacher/CuiZhen'
      - title: 'Chunyan Xu'
        url: '/pages/Teacher/XuChunyan'
      - title: 'Tong Zhang'
        url: '/pages/Teacher/ZhangTong'
      - title: 'Yong Li'
        url: '/pages/Teacher/LiYong'
  - title: 'Students'
    url: '/pages/Student'
  - title: 'Publications'
    url: '/pages/Publications'
    submenu:
      - title: '2020'
        url: '/pages/Publications/2020'
      - title: '2019'
        url: '/pages/Publications/2019'
      - title: '2018'
        url: '/pages/Publications/2018'
      - title: '2017'
        url: '/pages/Publications/2017'
      - title: '2016'
        url: '/pages/Publications/2016'
      - title: 'Before  2015'
        url: '/pages/Publications/before2015'

  - title: 'Resources'
    url: '/pages/Resource'



# Owner/author information
owner:
  name:           Njust
  site:           http://aronbordin.com
  avatar:         images/avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          you@email.com
# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.


# Social networking links used in author block underneath posts. Update and remove as you like.

# Background image to be tiled on all pages
background: 背景.jpg

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone:    America/New_York
#locale:      en_US
#future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
